CALL edit_password (1, 'xjfjhdhjsffe');
CALL search_for_company('Orange');
CALL search_for_company('Potato');
CALL search_for_job_by_title('Software Engineer');
CALL search_for_user_by_skill(1);
CALL view_applied_jobs(1);
CALL view_jobs_for_company(1);
CALL delete_company(15);
CALL delete_job(2);
CALL delete_job_needs_skill(7, 2);
CALL delete_skill(3);
CALL delete_user(2);
CALL delete_user_apply_for_job(1, 4);
CALL delete_user_blocks_user(5, 2);
CALL delete_user_friend_with_user(1, 18);
CALL delete_user_has_skill(1, 1);