-- Inserting jobs
CALL Insert_Job("1", 'Php Developer', "1");
CALL Insert_Job("2", 'IT Manager', "1");
CALL Insert_Job("3", 'Node Developer', "1");
CALL Insert_Job("4", 'Communication Engineer', "3");
CALL Insert_Job("5", 'Software Engineer', "2");
CALL Insert_Job("6", 'Project Manager', "1");
CALL Insert_Job("7", 'Front End Developer', "3");
CALL Insert_Job("8", 'Driver', "15");
CALL Insert_Job("9", 'Driver', "14");
CALL Insert_Job("10", 'Driver', "13");
CALL Insert_Job("11", 'Photographer', "6");
CALL Insert_Job("12", 'HR', "2");
CALL Insert_Job("13", 'Consultant', "10");
CALL Insert_Job("14", 'Software Intern', "2");
CALL Insert_Job("15", 'Database Admin', "3");
CALL Insert_Job("16", 'Junior Java Developer', "3");
CALL Insert_Job("17", 'Senior Mobile Developer', "4");
CALL Insert_Job("18", 'IT Engineer', "13");
CALL Insert_Job("19", 'Senior Android Developer', "12");
CALL Insert_Job("20", 'Data Analyst', "1");
CALL Insert_Job("21", 'Research Engineer', "1");
